// {
// "1": "Take care of your plants",
// "2": "start",
// "3": "sign in",
// "4": "sign up",
// "5": "Email address",
// "6": "password",
// "7": "Forgot your password ?",
// "8": "Login",
// "9": "or Login with",
// "10": "Don't have an account? Sing up",
// "11": "user name",
// "12": "Email ",
// "13": "password",
// "14": "Confirm password",
// "15": "Sign Up",
// "16": "or Sign up with",
// "17": "01.",
// "18": "Plant Scanning",
// "19": "Identify plants,research plant care",
// "20": "information , add your own plants.",
// "21": "02.",
// "22": "Plan for all plant care",
// "23": "No more withered plants due to ",
// "24": "forgotten watering .",
// "25": "03.",
// "26": "Disease Definition",
// "27": "Identify plant diseases and learn all ",
// "28": "about their prevention .",
// "29": "04.",
// "30": "Chatting with experts",
// "31": "Finding solutions for plants diseases ",
// "32": "and learn how to care of plants .",
// "33": "Forgot Password ?",
// "34": "Don't worry! It occurs. Please enter the email address linked with your account.",
// "35": "Enter your Email",
// "36": "Send code",
// "37": "Remember Password?",
// "38": "Login",
// "39": "Create new password",
// "40": "Your new password must be unique from those previously used.",
// "41": "New Password",
// "42": "Confirm Password",
// "43": "Reset Password",
// "44": "Password Changed!",
// "45": "Your password has been changed successfully.",
// "46": "Back to Log in",
// "47": "AI algorithm",
// "48": "Our algorithm recognizes plant ",
// "49": "and find diseases .It is also possible to",
// "50": "give tips on how to take care of plants",
// "51": "based on the huge plant database.",
// "52": "Recently added",
// "53": "You haven’t added",
// "54": "any plants yet .",
// "55": "Home",
// "56": "History",
// "57": "Chat bot",
// "58": "Profile",
// "59": "AI algorithm",
// "60": "Our algorithm recognizes plant ",
// "61": "and find diseases .It is also possible to",
// "62": "give tips on how to take care of plants",
// "63": "based on the huge plant database.",
// "64": "Recently added",
// "65": "History",
// "66": "Nothing was found!",
// "67": "You have not scan any plants yet.",
// "68": "Home",
// "69": "History",
// "70": "Chat bot",
// "71": "Profile",
// "72": "History",
// "73": "Home",
// "74": "History",
// "75": "Chat bot",
// "76": "Profile",
// "77": "You haven’t added any plants yet. ",
// "78": "Add a plant",
// "79": "Home",
// "80": "History",
// "81": "Chat bot",
// "82": "Profile",
// "83": "Added recently",
// "84": "Add more",
// "85": "Home",
// "86": "History",
// "87": "Chat bot",
// "88": "Profile",
// "89": "Add a plant to your history",
// "90": "Identify by camera",
// "91": "Identify by photo",
// "92": "Place the plant in the frame.",
// "93": "Make sure the image isn’t blurry.",
// "94": "Scan only one plant at a time .",
// "95": "If the plant is big , scan its leaves.",
// "96": "Got it",
// "97": "Treatment",
// "98": "Home",
// "99": "History",
// "100": "Chat bot",
// "101": "Profile",
// "102": "payment",
// "103": "Welcome to card",
// "104": "Choose Card",
// "105": "Visa",
// "106": "Master Card",
// "107": "PayPal",
// "108": "G pay",
// "109": "Choose Card",
// "110": "$ 999.00",
// "111": "Save credit card information for next time",
// "112": "Payment",
// "113": "payment Confirm",
// "114": "Thank you !",
// "115": "Successful your payment",
// "116": "check your email & track your product",
// "117": "Done",
// "118": "Treatment",
// "119": "Start tracking",
// "120": "Mosaic Verius",
// "121": "other plants",
// "122": "My plants",
// "123": "My plants",
// "124": "Chatbot",
// "125": "Hello i am your virtual guide ",
// "126": "and will help you",
// "127": "in planting.",
// "128": "Start",
// "129": "Profile",
// "130": "Last sync 5/5/22",
// "131": "Preferences",
// "132": "Language",
// "133": "Notification",
// "134": "Help",
// "135": "About",
// "136": "Log out",
// "137": "Language",
// "138": "Select your language",
// "139": "Notification",
// "140": "Clear",
// "141": "Home",
// "142": "History",
// "143": "Chat bot",
// "144": "Profile",
// "145": "Notification",
// "146": "Clear",
// "147": "There is no \nNotification",
// "148": "Home",
// "149": "History",
// "150": "Chat bot",
// "151": "Profile",
// "152": "Help",
// "153": "Help Center",
// "154": "If you want any help or faces any problems If you want any help or faces any problems ",
// "155": "with our app,",
// "156": " please go to chat bot",
// "157": "To Chatbot",
// "158": "About",
// "159": "Tgrow is the usable and great plant app that helps you to follow plant growth process. ",
// "160": "You can scan the plant, identify disease, and know the treatment that you can do to your plant.",
// "161": "To help you with topics that will be vague for you. Tgrow added chatbot that you can use it freely.",
// "162": "Also we added contacts of the experts who can help you in your inquiry.",
// "163": "Weekly Tips which added automatically to follow how you can grow healthy and freshness plant ",
// "164": "Log out",
// "165": "Are you sure you want to log out?",
// "166": "Log out",
// "167": "Cancel"
// }{
// "1": "اهتم بنباتاتك",
// "2": "ابدا",
// "3": "تسجيل الدخول",
// "4": "انشاء حساب",
// "5": "عنوان البريد الاليكتروني",
// "6": "كلمه المرور",
// "7": "نسيت كلمت المرور",
// "8": "تسجيل الدخول",
// "9": "السجيل بواسطه",
// "10": "ليس لدي حساب؟ انشاء حساب",
// "11": "اسم المستخدم",
// "12": "البريد الاليكتروني",
// "13": "كلمه المرور",
// "14": "تاكيد كلمه المرور",
// "15": "انشاء حساب",
// "16": "تسجيل دخول بواسطه",
// "17": "1",
// "18": "تصوير النبات",
// "19":"تحديد النباتات ، والبحث عن معلومات العناية",
// "20": " بالنباتات ، وإضافة النباتات الخاصة بك",
// "21": "2",
// "22": "خطة لجميع العناية بالنباتات",
// "23": "لا مزيد من النباتات الذابلة بسبب",
// "24": "نسيان الري ."
//
//
// }